
apiVersion: v1
kind: Service
metadata:
  name: modresortswar
  labels:
    app: modresortswar
spec:
  ports:
    - port: 9080
  selector:
    app: modresortswar
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: modresortswar
  name: modresortswar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: modresortswar
    spec:
      containers:
      - image: mycluster.icp:8500/default/modresortswar:latest
        name: modresortswar
        ports:
        - containerPort: 9080
          protocol: TCP
